In [2]:
print("Hello World")

s = "Hello World"
# reverse of a string witout any predefined functions
def reverse(s:str) -> str :
  reverse_str = ""
  for i in range(len(s)-1,-1,-1):
    reverse_str += s[i]
  return reverse_str
print(reverse(s))

Hello World
dlroW olleH


In [3]:
# Why numpy and pandas are required
# speed , structure and ecosystem
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = a + b
print(c)


[ 7  9 11 13 15]


In [4]:
# Two Dimensional Array

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# Array of Zeroes
new_matrix = np.zeros((2,3))
print(new_matrix)

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# Array of Ones
ones = np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
# Array with number
full_arr = np.full((2,3),7)
print(full_arr)

[[7 7 7]
 [7 7 7]]


In [8]:
# Random Numbers
random_arr = np.random.random((2,2))
print(random_arr)

[[0.07526758 0.57400642]
 [0.63750844 0.85308728]]


In [9]:
# Identity Matrix
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
# Array with range of values
range_arr = np.arange(0,10,2) # Start , Stop , Step
print(range_arr)


[0 2 4 6 8]


In [11]:
# Properties / Attributes in Numpy
# 1] Shape
print(identity.shape) # -> Rows,columns
# 2]Size
print(identity.size) # -> 9 elements
# 3]Datatype
print(identity.dtype) # -> int64 / float64
# 4]Number of Dimenstions
print(identity.ndim) # -> 2 dimensional so 2


(3, 3)
9
float64
2


In [12]:
# Accessing Arrays in numpy
array = np.array([1,2,3,4])
print(array[-1])
print(array[1::2])

# Accessing Multi Dimensional Array
print(matrix[1,2]) # Row , column

4
[2 4]
6


In [13]:
arr = np.array([0,10,20,30,40,50,60])
print(arr[1:4])
print(arr[:3])
print(arr[3:])
print(arr[::2])
print(arr[::-1])

arr = np.arange(1,13).reshape((3,4))
print(arr[2][1 : 3])

[10 20 30]
[ 0 10 20]
[30 40 50 60]
[ 0 20 40 60]
[60 50 40 30 20 10  0]
[10 11]


In [14]:
arr = np.arange(1,13) # Generates 12 elements (1 to 12)
print(arr)
matrix = arr.reshape(3,4)
cube = arr.reshape((2,2,3))
print("Original : ",arr)
print("Matrix : ",matrix)
print("Cube : ",cube)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Original :  [ 1  2  3  4  5  6  7  8  9 10 11 12]
Matrix :  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Cube :  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [15]:
a = np.array([10,20,30])
b = np.array([1,2,3])

print("Addition : ",a + b)
print("Subtraction : ",a - b)
print("Multiplication : ", a * b)
print("Division : ",a / b)
print("Exponentional : ",a ** 2)


Addition :  [11 22 33]
Subtraction :  [ 9 18 27]
Multiplication :  [10 40 90]
Division :  [10. 10. 10.]
Exponentional :  [100 400 900]


In [16]:
# Transpose Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [17]:
# converting single dimension to 2 dimension 
print("Original Matrix : ",matrix)
print()
print("Flatten Matrix : ",matrix.flatten())
print()
print("Array : ",arr)
print()
print("Square Root : ",np.sqrt(arr))
print()
print("Exponential : ",np.exp(arr))
print()
print("Log : ",np.log(arr))
print()
print("Absolute Value : ",np.abs(arr))

Original Matrix :  [[1 2 3]
 [4 5 6]
 [7 8 9]]

Flatten Matrix :  [1 2 3 4 5 6 7 8 9]

Array :  [ 1  2  3  4  5  6  7  8  9 10 11 12]

Square Root :  [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766 3.31662479 3.46410162]

Exponential :  [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04 5.98741417e+04 1.62754791e+05]

Log :  [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509 2.39789527 2.48490665]

Absolute Value :  [ 1  2  3  4  5  6  7  8  9 10 11 12]
