In [84]:
print("Hello World")

s = "Hello World"
# reverse of a string witout any predefined functions
def reverse(s:str) -> str :
    reverse_str = ""
    for i in range(len(s)-1,-1,-1):
        reverse_str += s[i]
    return reverse_str
print(reverse(s))

Hello World
dlroW olleH


In [85]:
# Why numpy and pandas are required
# speed , structure and ecosystem
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = a + b
print(c)

[ 7  9 11 13 15]


In [86]:
# Two Dimensional Array

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [87]:
# Array of Zeroes
new_matrix = np.zeros((2,3))
print(new_matrix)

[[0. 0. 0.]
 [0. 0. 0.]]


In [88]:
# Array of Ones
ones = np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [89]:
# Array with number
full_arr = np.full((2,3),7)
print(full_arr)

[[7 7 7]
 [7 7 7]]


In [90]:
# Random Numbers
random_arr = np.random.random((2,2))
print(random_arr)

[[0.94954781 0.39782999]
 [0.91069489 0.61973681]]


In [91]:
# Identity Matrix
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [92]:
# Array with range of values
range_arr = np.arange(0,10,2) # Start , Stop , Step
print(range_arr)

[0 2 4 6 8]


In [93]:
# Properties / Attributes in Numpy
# 1] Shape
print(identity.shape) # -> Rows,columns
# 2]Size
print(identity.size) # -> 9 elements
# 3]Datatype
print(identity.dtype) # -> int64 / float64
# 4]Number of Dimenstions
print(identity.ndim) # -> 2 dimensional so 2

(3, 3)
9
float64
2


In [94]:
# Accessing Arrays in numpy
array = np.array([1,2,3,4])
print(array[-1])
print(array[1::2])

# Accessing Multi Dimensional Array
print(matrix[1,2]) # Row , column

4
[2 4]
6


In [95]:
arr = np.array([0,10,20,30,40,50,60])
print(arr[1:4])
print(arr[:3])
print(arr[3:])
print(arr[::2])
print(arr[::-1])

arr = np.arange(1,13).reshape((3,4))
print(arr[2][1 : 3])

[10 20 30]
[ 0 10 20]
[30 40 50 60]
[ 0 20 40 60]
[60 50 40 30 20 10  0]
[10 11]


In [96]:
arr = np.arange(1,13) # Generates 12 elements (1 to 12)
print(arr)
matrix = arr.reshape(3,4)
cube = arr.reshape((2,2,3))
print("Original : ",arr)
print("Matrix : ",matrix)
print("Cube : ",cube)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Original :  [ 1  2  3  4  5  6  7  8  9 10 11 12]
Matrix :  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Cube :  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [97]:
a = np.array([10,20,30])
b = np.array([1,2,3])

print("Addition : ",a + b)
print("Subtraction : ",a - b)
print("Multiplication : ", a * b)
print("Division : ",a / b)
print("Exponentional : ",a ** 2)

Addition :  [11 22 33]
Subtraction :  [ 9 18 27]
Multiplication :  [10 40 90]
Division :  [10. 10. 10.]
Exponentional :  [100 400 900]


In [98]:
# Transpose Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [99]:
# converting single dimension to 2 dimension 
print("Original Matrix : ",matrix)
print()
print("Flatten Matrix : ",matrix.flatten())
print()
print("Array : ",matrix)
print()
print("Square Root : ",np.sqrt(matrix))
print()
print("Exponential : ",np.exp(matrix))
print()
print("Log : ",np.log(matrix))
print()
print("Absolute Value : ",np.abs(matrix))

Original Matrix :  [[1 2 3]
 [4 5 6]
 [7 8 9]]

Flatten Matrix :  [1 2 3 4 5 6 7 8 9]

Array :  [[1 2 3]
 [4 5 6]
 [7 8 9]]

Square Root :  [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]

Exponential :  [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Log :  [[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]

Absolute Value :  [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [100]:
# NOTE: Test 
print(matrix.flatten())

[1 2 3 4 5 6 7 8 9]


In [101]:
# NOTE: Similar to agregrate functions in munpy we also have some aggrgrate functions 
scores = np.array([70,80,90,100,60])
print("Sum : ",np.sum(scores))
print("Median : ",np.median(scores))
print("Mean : ",np.mean(scores))
print("Min : ",np.min(scores))
print("Max : ",np.max(scores))
print("Standard Deviation : ",np.std(scores))

Sum :  400
Median :  80.0
Mean :  80.0
Min :  60
Max :  100
Standard Deviation :  14.142135623730951


In [102]:

# NOTE: BroadCasting In Numpy
# DEF : BroadCasting allows numpy to perform opertaions between arrays with compatible shapes 
# Adding matrix with vector 
matrix = np.array([[1,2,3],[4,5,6]])
vector = np.array([10,20,30])
print("Matrix + Vector : ",matrix+vector)

Matrix + Vector :  [[11 22 33]
 [14 25 36]]


In [103]:
# NOTE: Axis tells numpy which dimesions to operate across 
# axis = 1 -> operates down rows,
# axis = 0 -> operates down cols 
example_matrix = np.array([[10,20,30],[40,50,60]])
print("Row Sum : ",np.sum(example_matrix,axis=1))
print("Columns sum : ",np.sum(example_matrix,axis=0))

Row Sum :  [ 60 150]
Columns sum :  [50 70 90]


In [104]:
# NOTE: Filtering using where() method 
example_vector = np.array([1,2,3,4,5,20,21,22,23,24,25])
print("Elements Greather that 20 : ",example_vector > 20) # It Returns boolen result array 
print("Values : ",example_vector[example_vector > 20])
# Using Where Without user defined message -> it returns only the  index of the elements that satsified the condition 
print("Using Where Method Without Any User Definied Message : ",np.where(example_vector > 20))
print("Using Where Method With User Definied Message : ",np.where(example_vector > 20,"Yes","No"))

Elements Greather that 20 :  [False False False False False False  True  True  True  True  True]
Values :  [21 22 23 24 25]
Using Where Method Without Any User Definied Message :  (array([ 6,  7,  8,  9, 10]),)
Using Where Method With User Definied Message :  ['No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes']


In [105]:
# NOTE: Combining Arrays 
# Some common methods include as : 
# 1] np.concatenate()
# 2] np.vstack()
# 3] np.hstack()
# 4] np.stack() -> creates a new axis 

matrix_1 = np.array([[1,2,3],[4,5,6]])
matrix_2 = np.array([[6,7,8],[9,10,11]])
print("Concatenation : ",np.concatenate([matrix_1,matrix_2]))
print("VStack : ",np.vstack([matrix_1,matrix_2]))
print("HStack : ",np.hstack([matrix_1,matrix_2]))
print("Stack : ",np.stack([matrix_1,matrix_2],axis=1))
print("Stack : ",np.stack([matrix_1,matrix_2],axis=0))


Concatenation :  [[ 1  2  3]
 [ 4  5  6]
 [ 6  7  8]
 [ 9 10 11]]
VStack :  [[ 1  2  3]
 [ 4  5  6]
 [ 6  7  8]
 [ 9 10 11]]
HStack :  [[ 1  2  3  6  7  8]
 [ 4  5  6  9 10 11]]
Stack :  [[[ 1  2  3]
  [ 6  7  8]]

 [[ 4  5  6]
  [ 9 10 11]]]
Stack :  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [108]:
# NOTE: Random number generation
rng = np.random.default_rng(42) 
print("Random Integers : ",rng.integers(1,10,size=5))
print("Random Floats : ",rng.random(5))
print("Normal Distribution : ",rng.normal(size=5))

Random Integers :  [1 7 6 4 4]
Random Floats :  [0.69736803 0.09417735 0.97562235 0.7611397  0.78606431]
Normal Distribution :  [-0.01680116 -0.85304393  0.87939797  0.77779194  0.0660307 ]


In [ ]:
# NOTE: Different types of multiplication 
# * -> it does element multiplication 
# @ -> it does rows multiplication 
# .dot() method does dot product between vectors only 
matrix_1 = np.array([[1,2],[3,4],[5,6]]) # (3,2)
matrix_2 = np.array([[6,7,8],[9,10,11]]) # (2,3)
print("Matrix Multiplication : ")
print(matrix_1 @ matrix_2) # (2 == 2) so matrix multiplication is possible 
matrix_1 = np.reshape(matrix_1,(2,3))
print("After Reshaping Matrix 1 : ")
print(matrix_1)
print("Element Multiplication : ")
print(matrix_1 * matrix_2)
vector_1 = np.array([1,2,3,4,5])
vector_2 = np.array([6,7,8,9,10])
print("Dot Product : ",vector_1 * vector_2)

Matrix Multiplication : 
[[ 24  27  30]
 [ 54  61  68]
 [ 84  95 106]]
After Reshaping Matrix 1 : 
[[1 2 3]
 [4 5 6]]
Element Multiplication : 
[[ 6 14 24]
 [36 50 66]]
[ 6 14 24 36 50]


In [119]:
# Nan Safe mean and sum 
nan_arr = np.array([10,20,30,np.nan,40,50])
print("Is Nan : ",np.isnan(nan_arr))
print("Mean Value : ",np.mean(nan_arr))
print("Nan Safe Mean : ",np.nanmean(nan_arr))
print("Sum : ",np.sum(nan_arr))
print("Nan Safe Sum : ",np.nansum(nan_arr))

Is Nan :  [False False False  True False False]
Mean Value :  nan
Nan Safe Mean :  30.0
Sum :  nan
Nan Safe Sum :  150.0
