In [1]:
#1. Create a NumPy array containing numbers from 10 to 100 with a step of 10.
import numpy as np 
array = np.linspace(10,100,10,dtype=int)
print(array)

[ 10  20  30  40  50  60  70  80  90 100]


In [2]:
#2. Create a 3 x 4 array of zeros.
array_of_zeros = np.zeros((3,4))
print(array_of_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
#3. Create an array and print its ndim, shape, size, and dtype.
example_vector = np.array([[10,20,30],[40,50,60]])
print("Array Dimensions : ",example_vector.ndim)
print("Array Shape : ",example_vector.shape)
print("Array Size : ",example_vector.size)
print("Data Type of Elements : ",example_vector.dtype)

Array Dimensions :  2
Array Shape :  (2, 3)
Array Size :  6
Data Type of Elements :  int64


In [4]:
#4. Extract the last element from a 1D array.
oneD_array = np.array([1,2,3,4,5])
print("Last Element of The 1D Array : ",oneD_array[-1])

Last Element of The 1D Array :  5


In [5]:
#5. Select the first two columns of a 2D array.
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[ : 2])

[[1 2 3]
 [4 5 6]]


In [6]:
#6. Reshape 12 numbers into a 3 x 4 matrix.
vector = np.arange(1,13).reshape(3,4)
print(vector)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
#7. Transpose a 2 x 3 matrix.
matrix = np.arange(1,7).reshape(2,3)
print("Transpose of Matrix (2,3) : ",matrix.T)

Transpose of Matrix (2,3) :  [[1 4]
 [2 5]
 [3 6]]


In [8]:
#8. Multiply every element of an array by 5.
print("Vector * 5 : ",vector * 5)

Vector * 5 :  [[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]]


In [9]:
#9. Create a feature matrix X with 5 samples and 3 features. Print its shape.
X = np.arange(1,16).reshape(5,3)
print("Shape of the Feature Matrix X : ",X.shape)

Shape of the Feature Matrix X :  (5, 3)


In [10]:
#10. Calculate the mean of each feature using axis=0
print("Mean of the elements in the axis = 0 : ",np.mean(X,axis=0))

Mean of the elements in the axis = 0 :  [7. 8. 9.]


In [13]:
#11. Filter all rows where the first feature is greater than 50.
X = np.array([[10, 20, 30],[60, 70, 80],[40, 50, 60],[90, 10, 20],[15, 25, 35]])
print("Filtered rows where first feature > 50: ",X[X[:,0] > 50])

Filtered rows where first feature > 50:  [[60 70 80]
 [90 10 20]]


In [ ]:
#12. Standardize every feature column.
mean = np.mean(X, axis=0)
std = np.std(X, axis=0)
X_standardized = (X - mean) / std
print("Mean of each feature column :", mean)
print("Std  of each feature column :", std)
print("Standardized Feature Matrix :\n", X_standardized)

In [ ]:
#13. Create a random matrix of shape (10, 4) using a fixed seed.
np.random.seed(42)
random_matrix = np.random.randn(10, 4)
print("Random Matrix of shape (10, 4):\n", random_matrix)
print("Shape :", random_matrix.shape)

In [ ]:
#14. Calculate X @ weights for a feature matrix and weight vector.
np.random.seed(42)
X_feat = np.random.randn(10, 4)
weights = np.array([0.5, -0.3, 0.8, 1.2])
result = X_feat @ weights
print("Feature Matrix X_feat shape :", X_feat.shape)
print("Weights                     :", weights)
print("X @ weights                 :", result)
print("Result Shape                :", result.shape)

In [ ]:
#15. Add a bias vector using broadcasting.
bias = np.array([1.0, 2.0, 3.0, 4.0])
X_biased = X_feat + bias
print("Bias vector             :", bias)
print("X_feat + bias (first 3 rows):\n", X_biased[:3])
print("Shape after adding bias :", X_biased.shape)

In [ ]:
#16. Calculate MSE between y_true and y_pred.
y_true = np.array([3.0, -0.5, 2.0, 7.0])
y_pred = np.array([2.5,  0.0, 2.0, 8.0])
mse = np.mean((y_true - y_pred) ** 2)
print("y_true                   :", y_true)
print("y_pred                   :", y_pred)
print("Mean Squared Error (MSE) :", mse)

In [ ]:
#17. Create a 28 x 28 grayscale image and print its shape.
grayscale_image = np.zeros((28, 28))
print("Grayscale Image Shape :", grayscale_image.shape)
print("(height x width) — single channel, no colour")

In [ ]:
#18. Create a batch of 64 RGB images of size 224 x 224.
batch = np.zeros((64, 224, 224, 3))
print("Batch of RGB Images Shape :", batch.shape)
print("(batch_size, height, width, channels) → 3 channels = R, G, B")

In [ ]:
#19. Create an array containing NaN and calculate its NaN-safe mean.
arr_with_nan = np.array([1.0, 2.0, np.nan, 4.0, 5.0, np.nan])
print("Array with NaN   :", arr_with_nan)
print("Normal mean      :", np.mean(arr_with_nan))     # returns nan
print("NaN-safe mean    :", np.nanmean(arr_with_nan))  # ignores NaN

In [ ]:
#20. Explain the difference between A * B and A @ B in your own words.
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("A =\n", A)
print("B =\n", B)
print()
print("A * B  (Element-wise multiplication):\n", A * B)
print()
print("A @ B  (Matrix multiplication / dot product):\n", A @ B)
print()
print("""
Difference:
  A * B  → Element-wise multiplication.
            Each element of A is multiplied by the SAME-POSITION element of B.
            Example: A[0][0] * B[0][0] = 1 * 5 = 5
            Both arrays must have the same shape.

  A @ B  → Matrix multiplication (dot product).
            Row of A is multiplied by column of B and the results are summed.
            Example: A[0] · B[:,0] = (1*5) + (2*7) = 19
            Shape rule: (m x n) @ (n x p) = (m x p)
""")